apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: photo-manager
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - gallery.sadclown.net
    secretName: photo-manager-tls
  rules:
  - host: gallery.sadclown.net
    http:
      paths:
      - path: /
        backend:
          serviceName: photo-manager
          servicePort: www
