kind: Service
apiVersion: v1
metadata:
  name: photo-manager
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  selector:
    app: photo-manager
  ports:
    - name: www
      protocol: TCP
      port: 80
      targetPort: http
