// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as ReactApollo from "react-apollo";

function make(client, children) {
  return ReasonReact.wrapJsForReason(ReactApollo.ApolloProvider, {
              client: client
            }, children);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
