// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as ApolloLinks from "../node_modules/reason-apollo/src/ApolloLinks.bs.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as ApolloLink from "apollo-link";
import * as ReasonApollo from "../node_modules/reason-apollo/src/ReasonApollo.bs.js";
import * as ApolloInMemoryCache from "../node_modules/reason-apollo/src/ApolloInMemoryCache.bs.js";
import * as ApolloLinkContext from "apollo-link-context";
import * as Cookies$PhotoManager from "./Cookies.bs.js";

var fragmentMatcher = ApolloInMemoryCache.createIntrospectionFragmentMatcher({
      __schema: {
        types: /* array */[{
            kind: "INTERFACE",
            name: "Child",
            possibleTypes: /* array */[
              {
                name: "Gallery"
              },
              {
                name: "Image"
              }
            ]
          }]
      }
    });

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(/* None */0, /* Some */[fragmentMatcher], /* () */0);

var context = ApolloLinkContext.setContext((function () {
        var token = Cookies$PhotoManager.readCookie("access_token");
        if (token) {
          return {
                  headers: {
                    authorization: "Bearer " + token[0]
                  }
                };
        } else {
          return { };
        }
      }));

function errorHandler(errorResponse) {
  if (errorResponse.networkError.statusCode === 401) {
    Cookies$PhotoManager.logOut(/* Some */[true], /* () */0);
    return ReasonReact.Router[/* push */0]("/login");
  } else {
    return /* () */0;
  }
}

var errorLink = ApolloLinks.createErrorLink(errorHandler);

var httpLink = ApolloLinks.createHttpLink("/graphiql", /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

var apolloClient = ReasonApollo.createApolloClient(inMemoryCache, ApolloLink.from(/* array */[
          context,
          errorLink,
          httpLink
        ]), /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

var Instance = ReasonApollo.CreateClient(/* module */[/* apolloClient */apolloClient]);

export {
  fragmentMatcher ,
  inMemoryCache ,
  context ,
  errorHandler ,
  errorLink ,
  httpLink ,
  Instance ,
  
}
/* fragmentMatcher Not a pure module */
