// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "../node_modules/bs-css-emotion/src/Css.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";

var containerCls = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.justifyContent(Css.center),
          /* :: */[
            Css.height(/* `percent */[
                  -119887163,
                  100.0
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var bounceDelay = Curry._1(Css.keyframes, /* :: */[
      /* tuple */[
        0,
        /* :: */[
          Css.transform(Css.scale(0.0, 0.0)),
          /* [] */0
        ]
      ],
      /* :: */[
        /* tuple */[
          80,
          /* :: */[
            Css.transform(Css.scale(0.0, 0.0)),
            /* [] */0
          ]
        ],
        /* :: */[
          /* tuple */[
            100,
            /* :: */[
              Css.transform(Css.scale(0.0, 0.0)),
              /* [] */0
            ]
          ],
          /* :: */[
            /* tuple */[
              40,
              /* :: */[
                Css.transform(Css.scale(1.0, 1.0)),
                /* [] */0
              ]
            ],
            /* [] */0
          ]
        ]
      ]
    ]);

var spinnerCls = Curry._1(Css.style, /* :: */[
      Css.width(Css.px(70)),
      /* :: */[
        Css.margin2(Css.px(0), Css.auto),
        /* :: */[
          Css.textAlign(Css.center),
          /* :: */[
            Css.selector("& > div", /* :: */[
                  Css.width(Css.px(18)),
                  /* :: */[
                    Css.height(Css.px(18)),
                    /* :: */[
                      Css.backgroundColor(Css.hex("333")),
                      /* :: */[
                        Css.borderRadius(/* `percent */[
                              -119887163,
                              100.0
                            ]),
                        /* :: */[
                          Css.display(Css.inlineBlock),
                          /* :: */[
                            Css.animationName(bounceDelay),
                            /* :: */[
                              Css.animationDuration(1400),
                              /* :: */[
                                Css.animationTimingFunction(Css.easeInOut),
                                /* :: */[
                                  Css.animationIterationCount(Css.infinite),
                                  /* :: */[
                                    Css.animationFillMode(Css.both),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var bounce1Cls = Curry._1(Css.style, /* :: */[
      Css.animationDelay(320),
      /* [] */0
    ]);

var bounce2Cls = Curry._1(Css.style, /* :: */[
      Css.animationDelay(160),
      /* [] */0
    ]);

function FullPageSpinner(Props) {
  return React.createElement("div", {
              className: containerCls
            }, React.createElement("div", {
                  className: spinnerCls
                }, React.createElement("div", {
                      className: bounce1Cls
                    }), React.createElement("div", {
                      className: bounce2Cls
                    }), React.createElement("div", undefined)));
}

var make = FullPageSpinner;

export {
  containerCls ,
  bounceDelay ,
  spinnerCls ,
  bounce1Cls ,
  bounce2Cls ,
  make ,
  
}
/* containerCls Not a pure module */
