// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as IndexJs from "./routes/gallery/index.js";

function make(_match, $$location, children) {
  return ReasonReact.wrapJsForReason(IndexJs.default, {
              location: $$location,
              match: _match
            }, children);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
