// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Css from "../node_modules/bs-css/src/Css.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as InfiniteScroll$PhotoManager from "./infiniteScroll.bs.js";

var component = ReasonReact.statelessComponent("GalleryBody");

var cls = Css.style(/* :: */[
      Css.margin4(Css.px(0), Css.auto, Css.px(40), Css.auto),
      /* [] */0
    ]);

function make(children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, InfiniteScroll$PhotoManager.make(/* Some */[cls], /* Some */[/* true */1], /* None */0, /* None */0, /* Some */[/* array */[
                        {
                          mq: "0px",
                          columns: 1,
                          gutter: 32
                        },
                        {
                          mq: (696).toString() + "px",
                          columns: 2,
                          gutter: 32
                        },
                        {
                          mq: (1028).toString() + "px",
                          columns: 3,
                          gutter: 32
                        },
                        {
                          mq: (1360).toString() + "px",
                          columns: 4,
                          gutter: 32
                        },
                        {
                          mq: (1692).toString() + "px",
                          columns: 5,
                          gutter: 32
                        },
                        {
                          mq: (1884).toString() + "px",
                          columns: 5,
                          gutter: 64
                        }
                      ]], children));
    });
  return newrecord;
}

export {
  component ,
  cls ,
  make ,
  
}
/* component Not a pure module */
