// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Css from "../node_modules/bs-css/src/Css.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as NavLink$PhotoManager from "./navLink.bs.js";
import * as GalleryItem$PhotoManager from "./galleryItem.bs.js";
import * as WaypointItem$PhotoManager from "./waypointItem.bs.js";

function make(name, slug) {
  var arg = function () {
    return GalleryItem$PhotoManager.make(/* Some */[/* false */0], (function (wrapClass, detailsClass) {
                  var link = "/gallery/" + slug;
                  return ReasonReact.element(/* None */0, /* None */0, NavLink$PhotoManager.make(link, /* Some */[wrapClass], /* None */0, /* array */[
                                  React.createElement("svg", {
                                        className: Css.style(/* :: */[
                                              Css.margin2(Css.px(0), Css.auto),
                                              /* :: */[
                                                Css.padding(Css.px(8)),
                                                /* :: */[
                                                  Css.display(Css.block),
                                                  /* [] */0
                                                ]
                                              ]
                                            ]),
                                        height: "200px",
                                        width: "200px",
                                        viewBox: "0 0 8 8"
                                      }, React.createElement("path", {
                                            id: "folder",
                                            d: "M0 0v2h8v-1h-5v-1h-3zm0 3v4.5c0 .28.22.5.5.5h7c.28 0 .5-.22.5-.5v-4.5h-8z"
                                          })),
                                  React.createElement("div", {
                                        className: detailsClass
                                      }, name)
                                ]));
                }));
  };
  return (function (param) {
      var func = function (param$1, param$2, param$3, param$4, param$5, param$6) {
        return WaypointItem$PhotoManager.make(param, name, slug, param$1, param$2, param$3, param$4, param$5, param$6);
      };
      return (function (param, param$1) {
          return Curry._5(func, param, param$1, 320, 275, arg);
        });
    });
}

export {
  make ,
  
}
/* Css Not a pure module */
