// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Css from "../node_modules/bs-css/src/Css.js";
import * as React from "react";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as Stars$PhotoManager from "./Stars.bs.js";
import * as GalleryItem$PhotoManager from "./GalleryItem.bs.js";
import * as CircleLoader$PhotoManager from "./CircleLoader.bs.js";
import * as WaypointItem$PhotoManager from "./WaypointItem.bs.js";

var component = ReasonReact.statelessComponent("GalleryItem");

var imgCls = Css.style(/* :: */[
      /* `declaration */[
        -434952966,
        /* tuple */[
          "objectFit",
          "cover"
        ]
      ],
      /* :: */[
        Css.display(Css.block),
        /* [] */0
      ]
    ]);

function make(onEnter, name, slug, thumbnail, rating, handleOpen, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, WaypointItem$PhotoManager.make(onEnter, name, slug, thumbnail, rating, 320, 295, (function () {
                        return ReasonReact.element(/* None */0, /* None */0, GalleryItem$PhotoManager.make(/* Some */[/* true */1], (function (wrapClass, detailsClass) {
                                          return React.createElement("div", {
                                                      className: wrapClass,
                                                      onClick: handleOpen
                                                    }, thumbnail ? React.createElement("img", {
                                                            className: imgCls,
                                                            height: "225",
                                                            src: thumbnail[0],
                                                            width: "300"
                                                          }) : ReasonReact.element(/* None */0, /* None */0, CircleLoader$PhotoManager.make(/* array */[])), React.createElement("div", {
                                                          className: detailsClass
                                                        }, React.createElement("div", undefined, name), ReasonReact.element(/* None */0, /* None */0, Stars$PhotoManager.make(slug, rating, /* array */[]))));
                                        })));
                      })));
    });
  return newrecord;
}

export {
  component ,
  imgCls ,
  make ,
  
}
/* component Not a pure module */
