// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "../node_modules/bs-css-emotion/src/Css.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as NavLink$PhotoManager from "./NavLink.bs.js";
import * as GalleryItem$PhotoManager from "./GalleryItem.bs.js";

var cls = Curry._1(Css.style, /* :: */[
      Css.margin2(Css.px(0), Css.auto),
      /* :: */[
        Css.padding(Css.px(8)),
        /* :: */[
          Css.display(Css.block),
          /* [] */0
        ]
      ]
    ]);

function outerCls(w, h) {
  return Curry._1(Css.style, /* :: */[
              Css.width(Css.px(w)),
              /* :: */[
                Css.height(Css.px(h)),
                /* [] */0
              ]
            ]);
}

function GalleryThumb(Props) {
  var name = Props.name;
  var slug = Props.slug;
  return React.createElement("div", {
              className: outerCls(320, 275)
            }, React.createElement(GalleryItem$PhotoManager.make, {
                  lightBG: false,
                  children: (function (wrapClass, detailsClass) {
                      var link = "/gallery/" + slug;
                      return React.createElement(NavLink$PhotoManager.make, {
                                  to: link,
                                  className: wrapClass,
                                  children: null
                                }, React.createElement("svg", {
                                      className: cls,
                                      height: "200px",
                                      width: "200px",
                                      viewBox: "0 0 8 8"
                                    }, React.createElement("path", {
                                          id: "folder",
                                          d: "M0 0v2h8v-1h-5v-1h-3zm0 3v4.5c0 .28.22.5.5.5h7c.28 0 .5-.22.5-.5v-4.5h-8z"
                                        })), React.createElement("div", {
                                      className: detailsClass
                                    }, name));
                    })
                }));
}

var make = GalleryThumb;

export {
  cls ,
  outerCls ,
  make ,
  
}
/* cls Not a pure module */
