// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Css from "../node_modules/bs-css/src/Css.js";
import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as Star$PhotoManager from "./star.bs.js";
import * as GalleryItem$PhotoManager from "./galleryItem.bs.js";
import * as CircleLoader$PhotoManager from "./circleLoader.bs.js";
import * as WaypointItem$PhotoManager from "./waypointItem.bs.js";

function stars(_filled, _total, _index, handleClick, _acc) {
  while(true) {
    var acc = _acc;
    var index = _index;
    var total = _total;
    var filled = _filled;
    var match = +(filled > 0);
    if (match !== 0) {
      _acc = /* :: */[
        ReasonReact.element(/* None */0, /* None */0, Star$PhotoManager.make(/* Some */[/* true */1], index, handleClick, /* array */[])),
        acc
      ];
      _index = index + 1 | 0;
      _total = total - 1 | 0;
      _filled = filled - 1 | 0;
      continue ;
      
    } else {
      var match$1 = +(total > 0);
      if (match$1 !== 0) {
        _acc = /* :: */[
          ReasonReact.element(/* None */0, /* None */0, Star$PhotoManager.make(/* Some */[/* false */0], index, handleClick, /* array */[])),
          acc
        ];
        _index = index + 1 | 0;
        _total = total - 1 | 0;
        continue ;
        
      } else {
        return List.rev(acc);
      }
    }
  };
}

function handleClickStar(submitRating, slug, i, $$event) {
  $$event.stopPropagation();
  return Curry._1(submitRating, {
              slug: slug,
              rating: i
            });
}

function make(onEnter, name, slug, thumbnail, rating, handleOpen, submitRating) {
  return (function (param) {
      return WaypointItem$PhotoManager.make(onEnter, name, slug, thumbnail, rating, 320, 295, (function () {
                    return GalleryItem$PhotoManager.make(/* Some */[/* true */1], (function (wrapClass, detailsClass) {
                                  var stars$1 = rating ? stars(rating[0], 5, 1, (function (param, param$1) {
                                            return handleClickStar(submitRating, slug, param, param$1);
                                          }), /* [] */0) : stars(0, 5, 1, (function (param, param$1) {
                                            return handleClickStar(submitRating, slug, param, param$1);
                                          }), /* [] */0);
                                  return React.createElement("div", {
                                              className: wrapClass,
                                              onClick: handleOpen
                                            }, thumbnail ? React.createElement("img", {
                                                    className: Css.style(/* :: */[
                                                          /* `declaration */[
                                                            -434952966,
                                                            /* tuple */[
                                                              "objectFit",
                                                              "cover"
                                                            ]
                                                          ],
                                                          /* :: */[
                                                            Css.display(Css.block),
                                                            /* [] */0
                                                          ]
                                                        ]),
                                                    height: "225",
                                                    src: thumbnail[0],
                                                    width: "300"
                                                  }) : ReasonReact.element(/* None */0, /* None */0, CircleLoader$PhotoManager.make(/* array */[])), React.createElement("div", {
                                                  className: detailsClass
                                                }, React.createElement("div", undefined, name), ReasonReact.createDomElement("div", { }, $$Array.of_list(stars$1))));
                                }));
                  }), param);
    });
}

export {
  stars ,
  handleClickStar ,
  make ,
  
}
/* Css Not a pure module */
