// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as Js_null_undefined from "../node_modules/bs-platform/lib/es6/js_null_undefined.js";
import * as ReactVirtualized from "react-virtualized";

function make(autoHeight, className, cellRenderer, columnCount, columnWidth, height, isScrolling, onScroll, rowCount, rowHeight, scrollTop, width, _) {
  return ReasonReact.wrapJsForReason(ReactVirtualized.Grid, {
              autoHeight: Js_null_undefined.fromOption(autoHeight),
              className: Js_null_undefined.fromOption(className),
              cellRenderer: cellRenderer,
              columnCount: columnCount,
              columnWidth: columnWidth,
              onScroll: Js_null_undefined.fromOption(onScroll),
              height: height,
              isScrolling: Js_null_undefined.fromOption(isScrolling),
              rowCount: rowCount,
              rowHeight: rowHeight,
              scrollTop: Js_null_undefined.fromOption(scrollTop),
              width: width
            }, /* array */[]);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
