// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE


var Location = /* module */[];

var State = /* module */[];

var History = /* module */[
  /* Location */Location,
  /* State */State
];

export {
  History ,
  
}
/* No side effect */
