// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var $$Location = { };

var State = { };

var $$History = {
  $$Location: $$Location,
  State: State
};

export {
  $$History ,
  
}
/* No side effect */
