// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE

import * as Css from "../node_modules/bs-css/src/Css.js";
import * as Json from "../node_modules/@glennsl/bs-json/src/Json.bs.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as ReactDOMRe from "../node_modules/reason-react/src/ReactDOMRe.js";
import * as Json_decode from "../node_modules/@glennsl/bs-json/src/Json_decode.bs.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as DynamicImport from "../node_modules/bs-dynamic-import/src/DynamicImport.bs.js";
import * as ApolloProvider from "../node_modules/reason-apollo/src/ApolloProvider.bs.js";
import * as App$PhotoManager from "./App.bs.js";
import * as Client$PhotoManager from "./Client.bs.js";
import * as RegisterServiceWorker from "./registerServiceWorker";

function config(json) {
  return /* record */[/* sentry_dsn */Json_decode.field("sentry_dsn", Json_decode.string, json)];
}

var Decode = /* module */[/* config */config];

DynamicImport.$less$$bang$great(DynamicImport.$less$$great(DynamicImport.resolve(import("./Raven.bs.js")), (function (Raven) {
            fetch("/config").then((function (prim) {
                          return prim.text();
                        })).then((function (text) {
                        return Promise.resolve(config(Json.parseOrRaise(text)));
                      })).then((function (config) {
                      Curry._1(Raven[/* setup */0], config[/* sentry_dsn */0]);
                      return Promise.resolve(/* () */0);
                    })).catch((function (err) {
                    console.log("Error loading Raven. Bad response from server", err);
                    return Promise.resolve(/* () */0);
                  }));
            return /* () */0;
          })), (function (error) {
        console.log(error);
        return /* () */0;
      }));

Css.$$global("body, html", /* :: */[
      Css.fontFamily("'Lato', sans-serif"),
      /* :: */[
        Css.fontWeight(300),
        /* :: */[
          Css.lineHeight(1.5),
          /* :: */[
            Css.width(Css.pct(100.0)),
            /* :: */[
              Css.height(Css.pct(100.0)),
              /* :: */[
                Css.margin(Css.px(0)),
                /* :: */[
                  Css.backgroundColor(Css.hex("fafafa")),
                  /* :: */[
                    Css.color(Css.hex("333")),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

((require('react-photoswipe/dist/photoswipe.css')));

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, ApolloProvider.make(Client$PhotoManager.instance, /* array */[ReasonReact.element(undefined, undefined, App$PhotoManager.make(/* array */[]))])), "app-root");

ReasonReact.Router[/* push */0]("");

RegisterServiceWorker.register();

export {
  Decode ,
  
}
/*  Not a pure module */
