// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Css from "../node_modules/bs-css/src/Css.js";
import * as Json from "../node_modules/bs-json/src/Json.js";
import * as RavenJs from "raven-js";
import * as ReactDOMRe from "../node_modules/reason-react/src/ReactDOMRe.js";
import * as Json_decode from "../node_modules/bs-json/src/Json_decode.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as App$PhotoManager from "./app.bs.js";
import * as RegisterServiceWorker from "./registerServiceWorker";

function config(json) {
  return /* record */[/* sentry_dsn */Json_decode.field("sentry_dsn", Json_decode.string, json)];
}

var Decode = /* module */[/* config */config];

fetch("/config").then((function (prim) {
              return prim.text();
            })).then((function (text) {
            return Promise.resolve(config(Json.parseOrRaise(text)));
          })).then((function (config) {
          var ravenConfig = RavenJs.config(config[/* sentry_dsn */0]);
          ravenConfig.install();
          return Promise.resolve(/* () */0);
        })).catch((function (err) {
        console.log("Error loading Raven. Bad response from server", err);
        return Promise.resolve(/* () */0);
      }));

Css.$$global("body, html", /* :: */[
      Css.fontFamily("'Lato', sans-serif"),
      /* :: */[
        Css.fontWeight(300),
        /* :: */[
          Css.lineHeight(1.5),
          /* :: */[
            Css.width(Css.pct(100.0)),
            /* :: */[
              Css.height(Css.pct(100.0)),
              /* :: */[
                Css.margin(Css.px(0)),
                /* :: */[
                  Css.backgroundColor(Css.hex("fafafa")),
                  /* :: */[
                    Css.color(Css.hex("333")),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

((require('react-photoswipe/dist/photoswipe.css')));

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$PhotoManager.make(/* array */[])), "root");

ReasonReact.Router[/* push */0]("");

RegisterServiceWorker.default();

export {
  Decode ,
  
}
/*  Not a pure module */
