// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Link");

function handleClick(onClick, href, $$event) {
  if (onClick) {
    Curry._1(onClick[0], $$event);
  }
  if ($$event.defaultPrevented) {
    return 0;
  } else {
    $$event.preventDefault();
    return ReasonReact.Router[/* push */0](href);
  }
}

function make($staropt$star, href, onClick, children) {
  var className = $staropt$star ? $staropt$star[0] : "";
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.createDomElement("a", {
                  href: href,
                  onClick: (function (param) {
                      return handleClick(onClick, href, param);
                    }),
                  className: className
                }, children);
    });
  return newrecord;
}

export {
  component ,
  handleClick ,
  make ,
  
}
/* component Not a pure module */
