// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE

import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as Js_primitive from "../node_modules/bs-platform/lib/es6/js_primitive.js";
import * as ReasonApollo from "../node_modules/reason-apollo/src/ReasonApollo.bs.js";
import * as Js_null_undefined from "../node_modules/bs-platform/lib/es6/js_null_undefined.js";
import * as GalleryQueries$PhotoManager from "./GalleryQueries.bs.js";

var Query = ReasonApollo.CreateQuery([
      GalleryQueries$PhotoManager.MoreQuery[1],
      GalleryQueries$PhotoManager.MoreQuery[2]
    ]);

var component = ReasonReact.statelessComponent("LoadMoreWrapper");

function updateQuery(previousResult, newResults) {
  var match = newResults.fetchMoreResult;
  if (match !== undefined) {
    var match$1 = previousResult.gallery;
    var match$2 = match.gallery;
    var combinedGallery;
    if (match$1 == null) {
      combinedGallery = (match$2 == null) ? undefined : Js_primitive.some(match$2);
    } else if (match$2 == null) {
      combinedGallery = Js_primitive.some(match$1);
    } else {
      var match$3 = match$1.descendants;
      var match$4 = match$2.descendants;
      var combinedDescendants = (match$3 == null) ? (
          (match$4 == null) ? /* array */[] : match$4
        ) : (
          (match$4 == null) ? match$3 : $$Array.append(match$3, match$4)
        );
      combinedGallery = {
        id: match$1.id,
        name: match$1.name,
        path: match$1.path,
        slug: match$1.slug,
        descendants: Js_null_undefined.fromOption(combinedDescendants),
        __typename: match$1.__typename
      };
    }
    return {
            gallery: Js_null_undefined.fromOption(combinedGallery)
          };
  } else {
    return {
            gallery: null
          };
  }
}

function make(slug, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var loadMoreQuery = GalleryQueries$PhotoManager.MoreQuery[/* make */3](slug, /* array */[], /* () */0);
              return ReasonReact.element(undefined, undefined, Curry.app(Query[/* make */3], [
                              Js_primitive.some(loadMoreQuery.variables),
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              (function (param) {
                                  var fetchMore = param[/* fetchMore */5];
                                  var result = param[/* result */0];
                                  if (typeof result === "number") {
                                    return Curry._2(children, undefined, (function (param) {
                                                  return Curry._2(fetchMore, param, updateQuery);
                                                }));
                                  } else if (result.tag) {
                                    return Curry._2(children, result[0].gallery, (function (param) {
                                                  return Curry._2(fetchMore, param, updateQuery);
                                                }));
                                  } else {
                                    return Curry._2(children, undefined, (function (param) {
                                                  return Curry._2(fetchMore, param, updateQuery);
                                                }));
                                  }
                                })
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  Query ,
  component ,
  updateQuery ,
  make ,
  
}
/* Query Not a pure module */
