// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as Caml_obj from "../node_modules/bs-platform/lib/es6/caml_obj.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";

var component = ReasonReact.reducerComponent("LoadMoreCache");

function combine(gallery, moreGallery) {
  var match = gallery.descendants;
  var match$1 = moreGallery.descendants;
  var newDescendants;
  if (match) {
    var descendants = match[0];
    newDescendants = match$1 ? /* Some */[$$Array.append(descendants, match$1[0])] : /* Some */[descendants];
  } else {
    newDescendants = match$1 ? /* Some */[match$1[0]] : /* None */0;
  }
  return {
          id: gallery.id,
          name: gallery.name,
          path: gallery.path,
          slug: gallery.slug,
          descendants: newDescendants
        };
}

function make(gallery, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */(function (param) {
              var state = param[/* state */1];
              console.log("Prop Gallery", gallery);
              var match = state[/* gallery */0];
              if (match) {
                var oldGallery = match[0];
                if (gallery) {
                  var newGallery = gallery[0];
                  if (Caml_obj.caml_notequal(oldGallery, newGallery)) {
                    var combined = combine(oldGallery, newGallery);
                    return /* record */[/* gallery : Some */[combined]];
                  } else {
                    return state;
                  }
                } else {
                  return /* record */[/* gallery : Some */[oldGallery]];
                }
              } else if (gallery) {
                return /* record */[/* gallery : Some */[gallery[0]]];
              } else {
                return /* record */[/* gallery : None */0];
              }
            }),
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return Curry._1(children, self[/* state */1][/* gallery */0]);
            }),
          /* initialState */(function () {
              return /* record */[/* gallery */gallery];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_, _$1) {
              return /* NoUpdate */0;
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  component ,
  combine ,
  make ,
  
}
/* component Not a pure module */
