// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as Link$PhotoManager from "./Link.bs.js";

var component = ReasonReact.statelessComponent("NavLink");

function make(_to, className, onClick, children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Link$PhotoManager.make(className, _to, onClick, children));
    });
  return newrecord;
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
