// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "../node_modules/bs-platform/lib/es6/caml_option.js";
import * as Link$PhotoManager from "./Link.bs.js";

function NavLink(Props) {
  var _to = Props.to;
  var className = Props.className;
  var onClick = Props.onClick;
  var children = Props.children;
  var tmp = {
    href: _to,
    children: children
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return React.createElement(Link$PhotoManager.make, tmp);
}

var make = NavLink;

export {
  make ,
  
}
/* react Not a pure module */
