// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE

import * as ReactDom from "react-dom";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as ReactPhotoswipe from "react-photoswipe";
import * as Caml_builtin_exceptions from "../node_modules/bs-platform/lib/es6/caml_builtin_exceptions.js";

var component = ReasonReact.statelessComponent("PhotoSwipe");

function make($staropt$star, items, onClose, options, _) {
  var isOpen = $staropt$star !== undefined ? $staropt$star : false;
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var match = document.getElementById("modal-root");
              if (match == null) {
                throw [
                      Caml_builtin_exceptions.invalid_argument,
                      "ReactDOMRE.renderToElementWithId : no element of id 'modal-root' found in the HTML."
                    ];
              } else {
                var eta = ReasonReact.wrapJsForReason(ReactPhotoswipe.PhotoSwipe, {
                      isOpen: isOpen,
                      items: items,
                      onClose: onClose,
                      options: options
                    }, /* array */[]);
                return ReactDom.createPortal(ReasonReact.element(undefined, undefined, eta), match);
              }
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
