// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactDom from "react-dom";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as ReactPhotoswipe from "react-photoswipe";
import * as Caml_builtin_exceptions from "../node_modules/bs-platform/lib/es6/caml_builtin_exceptions.js";

function PhotoSwipe(Props) {
  var match = Props.isOpen;
  var isOpen = match !== undefined ? match : false;
  var items = Props.items;
  var onClose = Props.onClose;
  var options = Props.options;
  var match$1 = document.getElementById("modal-root");
  if (match$1 == null) {
    throw [
          Caml_builtin_exceptions.invalid_argument,
          "ReactDOMRE.renderToElementWithId : no element of id 'modal-root' found in the HTML."
        ];
  } else {
    return ReactDom.createPortal((function (eta) {
                    return ReasonReact.element(undefined, undefined, eta);
                  })(ReasonReact.wrapJsForReason(ReactPhotoswipe.PhotoSwipe, {
                        isOpen: isOpen,
                        items: items,
                        onClose: onClose,
                        options: options
                      }, /* array */[])), match$1);
  }
}

var make = PhotoSwipe;

export {
  make ,
  
}
/* react-dom Not a pure module */
