// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Js_boolean from "../node_modules/bs-platform/lib/es6/js_boolean.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as ReactPhotoswipe from "react-photoswipe";

function make($staropt$star, items, onClose, options, children) {
  var isOpen = $staropt$star ? $staropt$star[0] : /* false */0;
  return ReasonReact.wrapJsForReason(ReactPhotoswipe.PhotoSwipe, {
              isOpen: Js_boolean.to_js_boolean(isOpen),
              items: items,
              onClose: onClose,
              options: options
            }, children);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
