// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as ReactPhotoswipe from "react-photoswipe";

function make($staropt$star, items, onClose, options, children) {
  var isOpen = $staropt$star ? $staropt$star[0] : false;
  return ReasonReact.wrapJsForReason(ReactPhotoswipe.PhotoSwipe, {
              isOpen: isOpen,
              items: items,
              onClose: onClose,
              options: options
            }, children);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
