// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE

import * as RavenJs from "raven-js";

function setup(dsn) {
  RavenJs.config(dsn).install();
  return /* () */0;
}

export {
  setup ,
  
}
/* raven-js Not a pure module */
