// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Browser from "@sentry/browser";

function init(dsn) {
  Browser.init({
        dsn: dsn
      });
  return /* () */0;
}

export {
  init ,
  
}
/* @sentry/browser Not a pure module */
