// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "../node_modules/bs-platform/lib/es6/caml_option.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as ReasonApollo from "../node_modules/reason-apollo/src/ReasonApollo.bs.js";
import * as Star$PhotoManager from "./Star.bs.js";
import * as GalleryQueries$PhotoManager from "./GalleryQueries.bs.js";

var Mutation = ReasonApollo.CreateMutation({
      query: GalleryQueries$PhotoManager.RateImage.query,
      parse: GalleryQueries$PhotoManager.RateImage.parse
    });

function stars5(_filled, _total, _index, handleClick, _acc) {
  while(true) {
    var acc = _acc;
    var index = _index;
    var total = _total;
    var filled = _filled;
    if (filled > 0) {
      _acc = /* :: */[
        React.createElement(Star$PhotoManager.make, {
              filled: true,
              index: index,
              handleClick: handleClick
            }),
        acc
      ];
      _index = index + 1 | 0;
      _total = total - 1 | 0;
      _filled = filled - 1 | 0;
      continue ;
    } else if (total > 0) {
      _acc = /* :: */[
        React.createElement(Star$PhotoManager.make, {
              filled: false,
              index: index,
              handleClick: handleClick
            }),
        acc
      ];
      _index = index + 1 | 0;
      _total = total - 1 | 0;
      continue ;
    } else {
      return List.rev(acc);
    }
  };
}

function handleClickStar(mutation, slug, i, $$event) {
  $$event.stopPropagation();
  var ratingMutation = GalleryQueries$PhotoManager.RateImage.make(slug, i, /* () */0);
  Curry._4(mutation, Caml_option.some(ratingMutation.variables), undefined, undefined, /* () */0);
  return /* () */0;
}

function stars(rating, handleClick) {
  if (rating !== undefined) {
    return stars5(rating, 5, 1, handleClick, /* [] */0);
  } else {
    return stars5(0, 5, 1, handleClick, /* [] */0);
  }
}

function Stars(Props) {
  var slug = Props.slug;
  var rating = Props.rating;
  return React.createElement(Mutation.make, {
              children: (function (mutation, param) {
                  var result = param.result;
                  var rating$1;
                  if (typeof result === "number" || result.tag !== /* Data */1) {
                    rating$1 = rating;
                  } else {
                    var match = result[0].rateImage;
                    rating$1 = match !== undefined ? Caml_option.valFromOption(match).rating : rating;
                  }
                  return ReasonReact.createDomElement("div", { }, $$Array.of_list(stars(rating$1, (function (param, param$1) {
                                        return handleClickStar(mutation, slug, param, param$1);
                                      }))));
                })
            });
}

var make = Stars;

export {
  Mutation ,
  stars5 ,
  handleClickStar ,
  stars ,
  make ,
  
}
/* Mutation Not a pure module */
