// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as Star$PhotoManager from "./Star.bs.js";
import * as Client$PhotoManager from "./Client.bs.js";
import * as GalleryQueries$PhotoManager from "./GalleryQueries.bs.js";

function stars5(_filled, _total, _index, handleClick, _acc) {
  while(true) {
    var acc = _acc;
    var index = _index;
    var total = _total;
    var filled = _filled;
    var match = filled > 0;
    if (match) {
      _acc = /* :: */[
        ReasonReact.element(/* None */0, /* None */0, Star$PhotoManager.make(/* Some */[true], index, handleClick, /* array */[])),
        acc
      ];
      _index = index + 1 | 0;
      _total = total - 1 | 0;
      _filled = filled - 1 | 0;
      continue ;
    } else {
      var match$1 = total > 0;
      if (match$1) {
        _acc = /* :: */[
          ReasonReact.element(/* None */0, /* None */0, Star$PhotoManager.make(/* Some */[false], index, handleClick, /* array */[])),
          acc
        ];
        _index = index + 1 | 0;
        _total = total - 1 | 0;
        continue ;
      } else {
        return List.rev(acc);
      }
    }
  };
}

function handleClickStar(ratingMutation, mutate, i, $$event) {
  $$event.stopPropagation();
  return Curry._1(mutate, Curry._2(ratingMutation, i, /* () */0));
}

function stars(rating, handleClick) {
  if (rating) {
    return stars5(rating[0], 5, 1, handleClick, /* [] */0);
  } else {
    return stars5(0, 5, 1, handleClick, /* [] */0);
  }
}

var component = ReasonReact.statelessComponent("Stars");

function make(slug, rating, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(/* None */0, /* None */0, Curry._1(Client$PhotoManager.Instance[/* Mutation */2][/* make */2], (function (mutate, result) {
                                var partial_arg = GalleryQueries$PhotoManager.RateImage[/* make */8];
                                var ratingMutation = function (param, param$1) {
                                  return partial_arg(slug, param, param$1);
                                };
                                var rating$1;
                                if (typeof result === "number" || result.tag) {
                                  rating$1 = rating;
                                } else {
                                  var parse = Curry._2(ratingMutation, 0, /* () */0).parse;
                                  var match = Curry._1(parse, result[0]).rateImage;
                                  rating$1 = match ? match[0].rating : rating;
                                }
                                return ReasonReact.createDomElement("div", { }, $$Array.of_list(stars(rating$1, (function (param, param$1) {
                                                      return handleClickStar(ratingMutation, mutate, param, param$1);
                                                    }))));
                              })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var Mutation = 0;

export {
  stars5 ,
  handleClickStar ,
  stars ,
  Mutation ,
  component ,
  make ,
  
}
/* component Not a pure module */
