// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "../node_modules/bs-css-emotion/src/Css.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";

var cls = Curry._1(Css.style, /* :: */[
      Css.color(Css.hex("828282")),
      /* :: */[
        Css.cursor(/* pointer */-786317123),
        /* :: */[
          Css.padding2(Css.zero, Css.px(2)),
          /* [] */0
        ]
      ]
    ]);

function star(filled) {
  if (filled) {
    return "★";
  } else {
    return "☆";
  }
}

function Star(Props) {
  var match = Props.filled;
  var filled = match !== undefined ? match : false;
  var index = Props.index;
  var handleClick = Props.handleClick;
  var handleClickWithI = Curry._1(handleClick, index);
  return React.createElement("span", {
              className: cls,
              onClick: handleClickWithI
            }, filled ? "★" : "☆");
}

var make = Star;

export {
  cls ,
  star ,
  make ,
  
}
/* cls Not a pure module */
