// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Css from "../node_modules/bs-css/src/Css.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Star");

var cls = Css.style(/* :: */[
      Css.color(Css.hex("828282")),
      /* :: */[
        Css.cursor(/* pointer */-786317123),
        /* :: */[
          Css.padding2(Css.zero, Css.px(2)),
          /* [] */0
        ]
      ]
    ]);

function star(filled) {
  if (filled !== 0) {
    return "\xe2\x98\x85";
  } else {
    return "\xe2\x98\x86";
  }
}

function make($staropt$star, index, handleClick, _) {
  var filled = $staropt$star ? $staropt$star[0] : /* false */0;
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var handleClickWithI = Curry._1(handleClick, index);
      return React.createElement("span", {
                  className: cls,
                  onClick: handleClickWithI
                }, star(filled));
    });
  return newrecord;
}

export {
  component ,
  cls ,
  star ,
  make ,
  
}
/* component Not a pure module */
