// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as Css from "../node_modules/bs-css/src/Css.js";
import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_obj from "../node_modules/bs-platform/lib/es6/caml_obj.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as Waypoint$PhotoManager from "./Waypoint.bs.js";

function cls(w, h) {
  return Css.style(/* :: */[
              Css.width(Css.px(w)),
              /* :: */[
                Css.height(Css.px(h)),
                /* [] */0
              ]
            ]);
}

var component = ReasonReact.reducerComponentWithRetainedProps("WaypointItem");

function makeVisible(send) {
  return Curry._1(send, /* Visible */0);
}

function makeNotVisible(send) {
  return Curry._1(send, /* NotVisible */1);
}

function make(onEnter, onLeave, name, slug, thumbnail, rating, w, h, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */(function (param) {
              var match = param[/* newSelf */1];
              var match$1 = param[/* oldSelf */0];
              if (Caml_obj.caml_notequal(match$1[/* state */1], match[/* state */1])) {
                return true;
              } else {
                return Caml_obj.caml_notequal(match$1[/* retainedProps */2], match[/* retainedProps */2]);
              }
            }),
          /* render */(function (self) {
              var oEnter;
              if (onEnter) {
                var func = onEnter[0];
                oEnter = (function () {
                    Curry._1(func, /* () */0);
                    return Curry._1(self[/* send */3], /* Visible */0);
                  });
              } else {
                oEnter = (function () {
                    return Curry._1(self[/* send */3], /* Visible */0);
                  });
              }
              var oLeave;
              if (onLeave) {
                var func$1 = onLeave[0];
                oLeave = (function () {
                    Curry._1(func$1, /* () */0);
                    return Curry._1(self[/* send */3], /* NotVisible */1);
                  });
              } else {
                oLeave = (function () {
                    return Curry._1(self[/* send */3], /* NotVisible */1);
                  });
              }
              return ReasonReact.element(/* None */0, /* None */0, Waypoint$PhotoManager.make(/* Some */[oEnter], /* Some */[oLeave], "-400px", "200px", false, /* array */[React.createElement("div", {
                                    className: cls(w, h)
                                  }, Curry._1(children, self[/* state */1][/* visible */0]))]));
            }),
          /* initialState */(function () {
              return /* record */[/* visible */false];
            }),
          /* retainedProps : record */[
            /* name */name,
            /* slug */slug,
            /* thumbnail */thumbnail,
            /* rating */rating
          ],
          /* reducer */(function (action, _) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[/* visible */false]]);
              } else {
                return /* Update */Block.__(0, [/* record */[/* visible */true]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  cls ,
  component ,
  makeVisible ,
  makeNotVisible ,
  make ,
  
}
/* component Not a pure module */
