// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Js_boolean from "../node_modules/bs-platform/lib/es6/js_boolean.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as ReactWaypoint from "react-waypoint";
import * as Js_null_undefined from "../node_modules/bs-platform/lib/es6/js_null_undefined.js";

function make(onEnter, bottomOffset, topOffset, fireOnRapidScroll, children) {
  return ReasonReact.wrapJsForReason(ReactWaypoint.default, {
              onEnter: Js_null_undefined.fromOption(onEnter),
              bottomOffset: bottomOffset,
              topOffset: topOffset,
              fireOnRapidScroll: Js_boolean.to_js_boolean(fireOnRapidScroll)
            }, children);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
