// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE

import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as ReactVirtualized from "react-virtualized";

function make(children) {
  return ReasonReact.wrapJsForReason(ReactVirtualized.WindowScroller, { }, children);
}

export {
  make ,
  
}
/* ReasonReact Not a pure module */
