// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Jest from "../node_modules/@glennsl/bs-jest/src/jest.js";

Jest.test("addition", (function (param) {
        return Jest.Expect.toBe(7, Jest.Expect.expect(7));
      }));

export {
  
}
/*  Not a pure module */
