// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Jest from "../node_modules/@glennsl/bs-jest/src/jest.js";
import * as Utils$PhotoManager from "../src/Utils.bs.js";

Jest.describe("chunkList", (function (param) {
        Jest.test("chunk by 1", (function (param) {
                return Jest.Expect.toEqual(/* :: */[
                            /* :: */[
                              1,
                              /* [] */0
                            ],
                            /* :: */[
                              /* :: */[
                                2,
                                /* [] */0
                              ],
                              /* :: */[
                                /* :: */[
                                  3,
                                  /* [] */0
                                ],
                                /* :: */[
                                  /* :: */[
                                    4,
                                    /* [] */0
                                  ],
                                  /* :: */[
                                    /* :: */[
                                      5,
                                      /* [] */0
                                    ],
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ], Jest.Expect.expect(Utils$PhotoManager.chunkList(1, /* :: */[
                                    1,
                                    /* :: */[
                                      2,
                                      /* :: */[
                                        3,
                                        /* :: */[
                                          4,
                                          /* :: */[
                                            5,
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("chunk by 2", (function (param) {
                return Jest.Expect.toEqual(/* :: */[
                            /* :: */[
                              1,
                              /* :: */[
                                2,
                                /* [] */0
                              ]
                            ],
                            /* :: */[
                              /* :: */[
                                3,
                                /* :: */[
                                  4,
                                  /* [] */0
                                ]
                              ],
                              /* :: */[
                                /* :: */[
                                  5,
                                  /* [] */0
                                ],
                                /* [] */0
                              ]
                            ]
                          ], Jest.Expect.expect(Utils$PhotoManager.chunkList(2, /* :: */[
                                    1,
                                    /* :: */[
                                      2,
                                      /* :: */[
                                        3,
                                        /* :: */[
                                          4,
                                          /* :: */[
                                            5,
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("chunk by 3", (function (param) {
                return Jest.Expect.toEqual(/* :: */[
                            /* :: */[
                              1,
                              /* :: */[
                                2,
                                /* :: */[
                                  3,
                                  /* [] */0
                                ]
                              ]
                            ],
                            /* :: */[
                              /* :: */[
                                4,
                                /* :: */[
                                  5,
                                  /* [] */0
                                ]
                              ],
                              /* [] */0
                            ]
                          ], Jest.Expect.expect(Utils$PhotoManager.chunkList(3, /* :: */[
                                    1,
                                    /* :: */[
                                      2,
                                      /* :: */[
                                        3,
                                        /* :: */[
                                          4,
                                          /* :: */[
                                            5,
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        return Jest.test("chunk by 4", (function (param) {
                      return Jest.Expect.toEqual(/* :: */[
                                  /* :: */[
                                    1,
                                    /* :: */[
                                      2,
                                      /* :: */[
                                        3,
                                        /* :: */[
                                          4,
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ],
                                  /* :: */[
                                    /* :: */[
                                      5,
                                      /* [] */0
                                    ],
                                    /* [] */0
                                  ]
                                ], Jest.Expect.expect(Utils$PhotoManager.chunkList(4, /* :: */[
                                          1,
                                          /* :: */[
                                            2,
                                            /* :: */[
                                              3,
                                              /* :: */[
                                                4,
                                                /* :: */[
                                                  5,
                                                  /* [] */0
                                                ]
                                              ]
                                            ]
                                          ]
                                        ])));
                    }));
      }));

export {
  
}
/*  Not a pure module */
