// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Jest from "../node_modules/@glennsl/bs-jest/src/jest.js";
import * as Utils$PhotoManager from "../src/Utils.bs.js";

describe("chunkList", (function () {
        return Jest.test("chunk by 1", (function () {
                      return Jest.Expect[/* toBe */2](/* :: */[
                                  /* :: */[
                                    1,
                                    /* [] */0
                                  ],
                                  /* :: */[
                                    /* :: */[
                                      2,
                                      /* [] */0
                                    ],
                                    /* :: */[
                                      /* :: */[
                                        3,
                                        /* [] */0
                                      ],
                                      /* :: */[
                                        /* :: */[
                                          4,
                                          /* [] */0
                                        ],
                                        /* :: */[
                                          /* :: */[
                                            5,
                                            /* [] */0
                                          ],
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ]
                                ], Jest.Expect[/* expect */0](Utils$PhotoManager.chunkList(1, /* :: */[
                                          1,
                                          /* :: */[
                                            2,
                                            /* :: */[
                                              3,
                                              /* :: */[
                                                4,
                                                /* :: */[
                                                  5,
                                                  /* [] */0
                                                ]
                                              ]
                                            ]
                                          ]
                                        ])));
                    }));
      }));

export {
  
}
/*  Not a pure module */
